apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-sms
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-sms/
  liveness:
    path: /rekrutteringsbistand-sms/internal/actuator/health
    initialDelay: 20
  readiness:
    path: /rekrutteringsbistand-sms/internal/actuator/health
    initialDelay: 20
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-sms
        mountPath: /secret/serviceuser
      - kvPath: /kv/preprod/fss/rekrutteringsbistand-sms/default
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  webproxy: true
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-sms/internal/actuator/prometheus
