server:
  port: 8080
  servlet.context-path: /rekrutteringsbistand-sms

management:
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: /internal/actuator
  endpoint.health.show-details: always

spring:
  application:
    name: rekrutteringsbistand-sms
  profiles.active: lokal
  jmx:
    enabled: false
