spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver

no.nav.security.jwt:
  issuer.isso:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    accepted_audience: 9b4e07a3-4f4c-4bab-b866-87f62dff480d
    cookiename: isso-idtoken
    proxyurl: http://webproxy.nais:8088
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy.nais:8088

rekrutteringsbistand:
  database:
    url: jdbc:postgresql://A01DBVL011.adeo.no:5432/rekrutteringsbistand-sms
    vault-sti: postgresql/prod-fss
  altinn-varsel:
    uri: https://pep-gw.oera.no:9443/ekstern/altinn/notificationagencyexternalbasic/v1
  sts:
    username: ${serviceuser.username}
    password: ${serviceuser.password}
    ws-uri: https://sts.adeo.no/SecurityTokenServiceProvider/
  unleash:
    unleash-uri: https://unleash.nais.io/api/
