spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver

no.nav.security.jwt:
  issuer.isso:
    discoveryurl: https://login.microsoftonline.com/NAVQ.onmicrosoft.com/.well-known/openid-configuration
    accepted_audience: 38e07d31-659d-4595-939a-f18dce3446c5
    cookiename: isso-idtoken
    proxyurl: http://webproxy.nais:8088

rekrutteringsbistand:
  database:
    database-navn: rekrutteringsbistand-sms
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  altinn-varsel:
    uri: https://pep-gw-q1.oera-q.local:9443/ekstern/altinn/notificationagencyexternalbasic/v1
  sts:
    username: ${serviceuser.username}
    password: ${serviceuser.password}
    ws-uri: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
  unleash:
    unleash-uri: https://unleash.nais.adeo.no/api/
