apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: rekrutteringsbistand-sms-alert
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
      prependText: 'rekrutteringsbistand-sms: '
  alerts:
    - alert: Feil ved sending av SMS via Altinn
      expr: sum(increase(rekrutteringsbistand_sms_feilet_total[5m])) > 0
      for: 1m
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
    - alert: Applikasjonen er nede (ingen Kubernetes-pods er oppe)
      expr: sum(up{app="rekrutteringsbistand-sms", job="kubernetes-pods"}) == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
    - alert: Økning log level ERROR
      severity: danger
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-sms",log_level=~"Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-sms"}[3m]))) > 1
      for: 3m
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
    - alert: Økning log level WARNING
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-sms",log_level=~"Warning"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="rekrutteringsbistand-sms"}[3m]))) > 20
      for: 3m
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
    - alert: Feil i selftest
      severity: danger
      expr: selftests_aggregate_result_status{app="rekrutteringsbistand-sms"} > 0
      for: 1m
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
    - alert: Økning HTTP serverfeil (5xx responser)
      severity: danger
      expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^5\\d\\d", backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-sms/*"}[3m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-sms/*"}[3m])))) > 1
      for: 3m
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
    - alert: Økning HTTP klientfeil (4xx responser andre enn 401)
      severity: warning
      expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^4\\d[0,2-9]", backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-sms/*"}[3m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"arbeidsgiver.nais.*/rekrutteringsbistand-sms/*"}[3m])))) > 20
      for: 3m
      action: "Kibana: https://logs.adeo.no/goto/c35f1545a01fc97aa82e4cfe836f1683"
