apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rekrutteringsbistand-sms
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: rekrutteringsbistand-sms
      rules:
        - alert: rekrutteringsbistand-sms
          expr: kube_deployment_status_replicas_available{deployment="rekrutteringsbistand-sms"} == 0
          for: 10s
          annotations:
            summary: Appen er nede
            action: "https://logs.adeo.no/app/r/s/l4gq0"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-sms
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-sms", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.adeo.no/app/r/s/l4gq0"
          labels:
            namespace: toi
            severity: critical

        - alert: rekrutteringsbistand-sms
          expr: sum(increase(log_messages_errors{app="rekrutteringsbistand-sms", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.adeo.no/app/r/s/l4gq0"
          labels:
            namespace: toi
            severity: warning
