apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-sms
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/rekrutteringsbistand-sms/
    - https://rekrutteringsbistand-sms.dev-fss-pub.nais.io/rekrutteringsbistand-sms/
  liveness:
    path: /rekrutteringsbistand-sms/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /rekrutteringsbistand-sms/internal/actuator/health
    initialDelay: 30
  preStopHookPath: /rekrutteringsbistand-sms/internal/preStopHook
  replicas:
    min: 1
    max: 1
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srv-rekbis-sms
        mountPath: /secret/serviceuser
      - kvPath: /kv/preprod/fss/rekrutteringsbistand-sms/toi
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: 67a06857-0028-4a90-bf4c-9c9a92c7d733 # ModiaGenerellTilgang
          - id: 554a66fb-fbec-4b92-90c1-0d9c085c362c # ModiaOppfølging
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-container
          cluster: dev-gcp
        - application: rekrutteringsbistand
          cluster: dev-gcp
    outbound:
      rules:
        - application: rekrutteringsbistand-kandidat-api
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: KANDIDAT_API_SCOPE
      value: api://dev-fss.toi.rekrutteringsbistand-kandidat-api/.default
  webproxy: true
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-sms/internal/actuator/prometheus
