apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: rekrutteringsbistand-sms
  namespace: toi
  labels:
    team: toi
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/rekrutteringsbistand-sms/
    - https://rekrutteringsbistand-sms.prod-fss-pub.nais.io/rekrutteringsbistand-sms/
  liveness:
    path: /rekrutteringsbistand-sms/internal/actuator/health
    initialDelay: 30
  readiness:
    path: /rekrutteringsbistand-sms/internal/actuator/health
    initialDelay: 30
  preStopHookPath: /rekrutteringsbistand-sms/internal/preStopHook
  replicas:
    min: 1
    max: 1
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srv-rekbis-sms
        mountPath: /secret/serviceuser
      - kvPath: /kv/prod/fss/rekrutteringsbistand-sms/toi
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: ea34edea-1e80-4759-a1d2-fbe696cf1709 # ModiaGenerellTilgang
          - id: b9bc6348-d25c-450d-85c2-044c0955fbe3 # ModiaOppfølging
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-container
          cluster: prod-gcp
        - application: rekrutteringsbistand
          cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  webproxy: true
  prometheus:
    enabled: true
    path: /rekrutteringsbistand-sms/internal/actuator/prometheus
